---

- src: https://github.com/superlumic/ansible-role-homebrew.git
  name: superlumic-homebrew

- src: https://github.com/superlumic/ansible-role-osx-defaults.git
  name: superlumic-osx-defaults

- src: https://github.com/superlumic/ansible-role-computername.git
  name: superlumic-computername

- src: https://github.com/superlumic/ansible-role-cli.git
  name: superlumic-cli
