---
  
  - name: Install general brew applications
    homebrew: name={{ item }} state=present
    with_items:
      - curl
      - wget

  - name: Install general cask applications
    homebrew_cask: name={{ item }} state=present
    with_items:
      - 1password
      - caffeine
      - dropbox
      - google-chrome
      - slack
      - spotify
