---
galaxy_info:
  author: Lee Fowler
  description: Ansible profile role for computer and operating system configuration
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - superlumic-computername
  - superlumic-osx-defaults
